### ISSUE TITLE
余分なGoogle-Serviceの情報の削除

### ISSUE THREAD

**Issue by Zudah228** [ymgn9314/schedule-adjust-app#7]
気にせんでいいと思ったけど、エラー出たので修正お願いします。
Xcode内にまだGoogle-Service.plist（GoogleService-Info-dev.plistでもGoogleService-Info-release.plistでもない前のGoogel-Service）の情報があるせいで以下のエラーが出てビルドできないので、
```
error: Build input file cannot be found: '/Users/tsudayamato/AndroidStudioProjects/drigro/yamagen/schedule-adjust-app/ios/Runner/GoogleService-Info.plist' (in target 'Runner' from project 'Runner')
```
Xcodeでこれ消しといて消しといてください
<img width="678" alt="スクリーンショット 2021-06-04 16 33 06" src="https://user-images.githubusercontent.com/62398366/120763935-addf1300-c552-11eb-9b36-fe0fb80c59aa.png">

**Comment by ymgn9314** [comment]
失礼しました。すぐに修正します。

**Comment by ymgn9314** [comment]
PR(#8 )を出しました。
